obj-m += hello.o

all:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules

clean:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean

load:
	sudo insmod hello.ko

unload:
	sudo rmmod hello

logs:
	dmesg | tail -20

.PHONY: all clean load unload logs
